JFLAGS = -g
JC = javac
JVM= java

.SUFFIXES: .java .class

.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
        MasterMind.java \
        Casilla.java \
        CodeBreaker.java \
        CodeMaker.java \
        CodePeg.java \
	Game.java \
	Jugador.java \
	KeyPeg.java \
	Ranking.java \
	Funciones.java \
	Pair.java \
        CodeBreakerDriver.java \
        CodeMakerDriver.java \
        CodePegDriver.java \
	CodePegStub.java \
	GameTest.java \
	JugadorDriver.java \
	JugadorStub.java \
	KeyPegDriver.java \
	KeyPegStub.java \
	RankingDriver.java \
	RankingStub.java \
	FuncionesDriver.java \
	PairDriver.java \
	Tests.java

MAIN = MasterMind
MAINTEST = Tests

default: classes

classes: $(CLASSES:.java=.class)

run: $(MAIN).class
	$(JVM) $(MAIN)

run_tests: $(MAINTESTS).class
		$(JVM) $(MAIN)

clean:
        $(RM) *.class